### ISSUE TITLE
I can't upload anything here.

### ISSUE THREAD

**Issue by chuebsch** [ecacomsig/Melk-2019#1]
I just tried to upload my slides here, but it says uploads are disabled.

**Comment by sbillinge** [comment]
Hi Christian,

We would normally be using a GitHub workflow to do things like this (fork,
clone, push, PR) , but if you are not familary to it it may be better to
send the slides to Harry or myself and we can load them.

One objective of the comsig having things on GitHub is also to broaden the
use of this platform for open source software in the community, so if you
are interested to learn the GitHub workflow I would be happy to help.
Please just let me know.

S

**Comment by chuebsch** [comment]
OK, made a pull request. Thank you!
